### ISSUE TITLE
Open source related BPM tools

### ISSUE THREAD

**Issue by datocrats-org** [goldmansachs/jdmn#226]
Dear @goldmansachs and Stephen Coster - Please open source your Global Workflow Infrastructure architecture and Workflow Engine, eTask, Workflow Designer, Forms Designer, Workflow Elements, and Workflow Control Centre. You are leading the world on implementing Camunda. I would use it to work on adapting infrastructure to work with the hyperledger blockchain smart contract logic to further verify the implementation.

**Comment by opatrascoiu** [comment]
Open sourcing the components you mentioned above is a long term objects.  Unfortunately, we don't have a timeline yet. Will keep you informed,.
