### ISSUE TITLE
Use translated model in JS applications

### ISSUE THREAD

**Issue by maximeag** [goldmansachs/jdmn#230]
Hello team,

I really like jDMN and let me congratulate you for all the work you made!

I have one question about translated model : **would it be possible to use a translated model in a JS application (by using GWT or other Java-to-JS tools) ?**

It may be a stupid question on my part (I'm really not a Java expert), but executing decisions in my JS application, without using REST api or a DMN JS engine, could be a great solution for managing business rules in a UX context.

**Comment by opatrascoiu** [comment]
You could try to jsweet (http://www.jsweet.org/getting-started/) to generate JS from the output of the jdmn maven plugin. I haven't tried, but they claim it works.

Hope this helps.

**Comment by maximeag** [comment]
Yes ! That's what I was looking for, thanks @opatrascoiu 👍
