### ISSUE TITLE
please support custom aggregators

### ISSUE THREAD

**Issue by jwaterloo2020** [goldmansachs/jdmn#283]
Please add support for custom aggregators when HIT policy is collect.

...

I would like to create custom aggregators in general but for now specifically I would like boolean logic aggregators. AND would allow any one false in a set of true false equivalent values to make the final result false. Similarly OR would allow any one true equivalent value to make the final result true. The AND would be great for allow/deny used in UIX and security domains. Better if these specific ones were advocated to be part of the standard.

**Comment by opatrascoiu** [comment]
Thanks for the suggestion. I will raise an issue for DMN 1.4.
