### ISSUE TITLE
jdmn code generation failing to parse a feel function

### ISSUE THREAD

**Issue by dbutler** [goldmansachs/jdmn#526]
### Expected Behavior

I expected a clean parse and java code generated for my dmn ageClassificationDtFeelFn.dmn.

I generated the dmn using Visual Code.  I have tested this DMN in a separate project, so I am pretty sure it is valid and parses and executes with red hat engine APIs.

It seems the generator has issues with Java and FEEL functions.

We tried the generator on some dmn files for our client, whose requirements are to use DMN embedded, with java like performance.  This tool could really help if we can get it to generate java for our dmn files.

### Actual Behavior

 MojoExecutionException: Cannot process template 'tree/bkm.ftl' for BKM 'dogYearsFn': Java method "com.gs.dmn.transformation.basic.BasicDMNToJavaTransformer.drgElementOutputType(org.omg.spec.dmn._20191111.model.TDRGElement)" threw an exception when invoked on com.gs.dmn.transformation.basic.BasicDMNToJavaTransformer object "com.gs.dmn.transformation.basic.BasicDMNToJavaTransformer@2dc39b53"; see cause exception in the Java stack trace.
[ERROR] 
[ERROR] ----
[ERROR] FTL stack trace ("~" means nesting-related):
[ERROR] 	- Failed at: ${transformer.drgElementOutputType(dr...  [in template "tree/bkm.ftl" at line 52, column 12]
[ERROR] ----: Expected function type for element 'dogYearsFn'. Found 'number'
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

### jDMN Version where this issue was observed

5.5.0

### Steps to reproduce the behavior

mvn clean generate-sources

[dmn-demo-jdmn-v2.zip](https://github.com/goldmansachs/jdmn/files/8411179/dmn-demo-jdmn-v2.zip)

**Comment by opatrascoiu** [comment]
jDMN reports a semantic error as the DMN model is not correct. The typeRef of the BKM.variable has to be a function type not a number. See correction below. 

```
  <dmn:businessKnowledgeModel id="_C45DDD2E-C590-4725-BFCF-8EE2BACC13D0" name="dogYearsFn">
    <dmn:extensionElements/>
<!--
    <dmn:variable id="_F4A8D2C7-AD97-420A-A679-2667133CC54E" name="dogYearsFn" typeRef="number"/>
-->
    <dmn:variable id="_F4A8D2C7-AD97-420A-A679-2667133CC54E" name="dogYearsFn" />
    <dmn:encapsulatedLogic id="_378A8CD9-B22B-4E9A-80D1-B15B83E21D60" kind="FEEL">
      <dmn:formalParameter id="_5D513353-D09F-4101-9164-D3032C505AD7" name="age" typeRef="number"/>
<!--
      <dmn:literalExpression id="_EB438EC5-CDEA-45A9-9FE4-422559BD90EE">
-->
      <dmn:literalExpression id="_EB438EC5-CDEA-45A9-9FE4-422559BD90EE" typeRef="number">
        <dmn:text>age * 7</dmn:text>
      </dmn:literalExpression>
    </dmn:encapsulatedLogic>
  </dmn:businessKnowledgeModel>

```
