### ISSUE TITLE
Reading/parser a DMN XML file

### ISSUE THREAD

**Issue by antonioluz** [goldmansachs/jdmn#91]
Hello,

following the example described in the FAQ:

```
DMNDialectDefinition dialect = new StandardDMNDialectDefinition();
DMNInterpreter interpreter = dialect.createDMNInterpreter(definitions);
String decisionName = ...;
RuntimeEnvironment runtimeEnvironment = RuntimeEnvironmentFactory.instance().makeEnvironment();
Object result = interpreter.evaluate(decisionName, runtimeEnvironment);
```
How can I parse a DMN file?
The variable definitions is of type TDefinitions, correct? How to work with it?
Could you describe an example where I make a parser from an xml DMN file, and then step variables to then perform the result evaluation?

**Thanks, and congratulations for the project.**

**Comment by opatrascoiu** [comment]
I will update the documentation with more info. In the meantime please have a look at AbstractDMNInterpreterTest.
